name: s_widgets
description: A Flutter package that gathers small custom widgets such as text buttons, loading indicators, and more.
issue_tracker: https://github.com/SoundSliced/s_widgets/issues
repository: https://github.com/SoundSliced/s_widgets
version: 1.1.0
homepage: https://github.com/SoundSliced/s_widgets

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  new_loading_indicator: ^1.2.1
  flutter_web_frame: ^1.0.0
  ticker_free_circular_progress_indicator: ^1.0.0
  soundsliced_tween_animation_builder: ^1.2.0
  soundsliced_dart_extensions: ^1.0.1
  flutter_animate: ^4.5.2
  sizer: ^3.1.3
  nb_utils: ^7.2.0
  s_button: ^1.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: