name: s_widgets
description: A Flutter package that gathers small custom widgets such as text buttons, loading indicators, and more.
issue_tracker: https://github.com/SoundSliced/s_widgets/issues
repository: https://github.com/SoundSliced/s_widgets
version: 2.0.1
homepage: https://github.com/SoundSliced/s_widgets

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^1.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
